### ISSUE TITLE
Mobile app integration

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#3]
- [x] Identifying protocol to use  
- [x] Identifying code architecture
- [x] Setting up Iroh and Veilid
- [ ] Initial integration into mobile app
- [ ] Connecting to front end 
- [ ] Backups in cloud server setup 
- [ ] Connect app to backups with UI 
- [ ] Test & QA 
- [ ] Identify bug fixes

Output: Functioning prototype of DWeb backend; (e.g. can it store media easily via Save?)

**Comment by writerly03** [comment]
Notes from Mauve on getting IPFS on Android: https://github.com/AgregoreWeb/agregore-mobile/blob/default/patches/0001-AG-IPFS-Daemon.patch

Relevant project examples, also from Mauve: https://github.com/AgregoreWeb/agregore-mobile/blob/default/patches/0001-AG-IPFS-Daemon.patch
https://github.com/Wapikoni-Technique/Natakanu/blob/master/app/core/Database.js
https://github.com/USHIN-Inc/ushin-db
https://git.sr.ht/~breatheoutbreathein/ushin-db/tree
https://github.com/consento-org/group

**Comment by RangerMauve** [comment]
Did some digging on how to replicate iroh over velid streams

https://github.com/n0-computer/iroh/blob/main/iroh/src/node/rpc.rs#L1180

This is a good starting point. We'll need to duplicate the methods and tweak them a bit since they are tightly coupled t quinn connections.

We may need a multiplexer library over top of veilid connections since it seems iroh doesn't have a multiplexer

**Comment by RangerMauve** [comment]
Close in favor of new items
