### ISSUE TITLE
Design code architecture

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#4]

**Comment by writerly03** [comment]
@RangerMauve's initial thoughts are here: https://hackmd.io/@s74XZjUBQDuPPS04AgPvow/rkDb3I-fC

**Comment by RangerMauve** [comment]
So after chatting with iroh folks it seems that iroh-docs is about to have some major changes so stability might be a bit iffy.

Instead of iroh docs we'll make use of veilid's DHT kv store. I'm going to keep the latest docs on the design in the [save-dweb-backend](https://github.com/OpenArchive/save-dweb-backend) github repo.

**Comment by writerly03** [comment]
Architecture has been confirmed and is diagramed here: https://github.com/OpenArchive/save-dweb-backend?tab=readme-ov-file#radmap
